# Используем официальный образ Ubuntu
FROM nginx:latest

# Указываем автора образа
LABEL authors="keeper"

# Обновляем пакеты и устанавливаем необходимые зависимости
RUN apt update && apt upgrade -y && \
    apt install -y mc && \
    apt clean && rm -rf /var/lib/apt/lists/*

# Устанавливаем рабочую директорию (по желанию)
WORKDIR /app

# Команда по умолчанию при запуске контейнера
CMD ["/bin/bash"]