# Используем базовый образ Ubuntu
FROM ubuntu:latest

# Устанавливаем необходимые пакеты
RUN apt update && apt install -y \
    wget \
    gnupg2 \
    software-properties-common \
    libxss1 \
    libappindicator3-1 \
    libatk-bridge2.0-0 \
    libgtk-3-0 \
    libx11-xcb1 \
    libxcb1 \
    libdbus-glib-1-2 \
    fonts-liberation \
    xdg-utils \
    libnspr4 \
    libnss3 \
    libxrandr2 \
    && apt clean && rm -rf /var/lib/apt/lists/*

# Добавляем репозиторий Google и устанавливаем Google Chrome
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && \
    apt update && apt install -y google-chrome-stable

# Устанавливаем рабочую директорию
WORKDIR /app

# Запускаем Google Chrome
CMD ["google-chrome-stable", "--no-sandbox"]
