version: '3.1'

services:

  pv321.storage:
    image: minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - ./volumes/store:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password

  pv321.mariaDb:
    # (in) 3306
    image: mariadb:latest
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  pv321.mySql:
    # (in) 3306
    image: mysql:latest
    ports:
      - "3320:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  pv321.pma:
    image: phpmyadmin
    ports:
      - "8088:80"
    environment:
      - PMA_ARBITRARY=1
