version: '3.1'

services:


  vp321.redis:
    image: redis
    ports:
      - "6379:6379"


  vp321.nginx:
    image: nginx:latest
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - vp321.api.csharp
      - vp321.api.express
      - vp321.api.http



  vp321.api.csharp:
    build:
      context: ./backend/csharp-api
    env_file:
      - ./jwt.env


  vp321.api.express:
    build:
      context: ./backend/express-api
    env_file:
      - ./jwt.env
    environment:
      - SERVER_NAME=ExpressServer
      - SERVER_PORT=4000


  vp321.api.http:
    build:
      context: ./backend/http-api
    env_file:
      - ./jwt.env
    environment:
      - SERVER_NAME=HttpServer
      - REDIS_HOST=vp321.redis

  vp321.api.hiload1:
    build:
      context: ./backend/http-api
    env_file:
      - ./jwt.env
    environment:
      - SERVER_NAME=HiLoad First
      - REDIS_HOST=vp321.redis

  vp321.api.hiload2:
    build:
      context: ./backend/http-api
    env_file:
      - ./jwt.env
    environment:
      - SERVER_NAME=HiLoad Second
      - REDIS_HOST=vp321.redis